### ISSUE TITLE
Feature Request: Recipe Keywords

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#101]
Similar to: #43, I would like to add `keywords` to the recipe JSON schema. This would be an optional array of strings so we can support adding "keywords" to recipes. This will allow us to add search filtering options.

For example:
```json
"keywords": [
    "alcoholic",
    "coffee"
]
```

This requires 3 parts:
* Update the JSON recipe template
* Update the recipe component to display the keywords (if provided) using [Bootstrap badges](https://bootstrap-vue.js.org/docs/components/badge)
* Update documentation in [CONTRIBUTING.md](https://github.com/alfg/opendrinks/blob/master/CONTRIBUTING.md).

The keyword badges can appear after the instructions, but before the optional source url.

Open to suggestions.

**Comment by VVNoodle** [comment]
Looking at it! will PR

**Comment by alfg** [comment]
#110 

Thanks @VVNoodle !
