### ISSUE TITLE
Feature Request: Search by Ingredients

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#102]
As a user, I would like to search by drink ingredients. For example, if I search `vodka`, then the search results should return back related drinks with `vodka` in their `ingredients` list.

This should be implemented on the "Search" view. The UI is open to suggestions, but should take advantage of Bootstrap Vue if possible and will require extending the RecipeFind.vue component.

Since this is a static website, it will all be done in JS using the JSON recipes.

Feel free to discuss here for ideas.

**Comment by TobyAsE** [comment]
I'd like to tackle this challenge.

**Comment by alfg** [comment]
#116

**Comment by PatrickLohan** [comment]
Checkboxes available for search filtering now available.
Bug encountered: not showing recipes by ingredient if they have that ingredient also in title, e.g. Vodka Martini, or Banana Smoothie

**Comment by alfg** [comment]
@PatrickLohan Nice catch. Can you open this bug as an issue?

**Comment by PatrickLohan** [comment]
Updated post. Now I know I can reference issue and create in one go haha!
