### ISSUE TITLE
Welcome to Hacktoberfest 2021! 🎃

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#1051]
![Hacktoberfest_final_2color-06 copy](https://user-images.githubusercontent.com/702541/135552704-4fae106c-4f9c-4aa1-969e-e7b60852769b.png)

# Welcome to [Hacktoberfest](https://hacktoberfest.digitalocean.com/) 2021!

We're looking for contributors to submit a drink recipe of their choice! Also feel free to suggest any **changes**, **bug fixes**, or **feature requests**! All merged pull requests will be published to https://opendrinks.io/.

See release notes from our previous Hacktoberfest contributions:
https://github.com/alfg/opendrinks/releases/tag/v1.0.0 - Thank you Hacktoberfest 2019!
https://github.com/alfg/opendrinks/releases/tag/v2.0.0 - Thank you Hacktoberfest 2020!

More issues will be created soon with varying difficulty levels. Check back for updates!

* Be sure to sign up at https://hacktoberfest.digitalocean.com
* [Create a Pull Request ](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) **between October 1-31** of 2021 to count towards your 4 Pull Requests.
* See [Contributing Guidelines](https://github.com/alfg/opendrinks/blob/master/CONTRIBUTING.md)
* See https://hacktoberfest.digitalocean.com/faq for more details
* Happy Hacking! 🎃 

**:warning: Please note, any spam pull requests will be marked as invalid and will not count towards your 4 PRs.**

❓ Feel free to comment or ask any questions here as well.

⭐ Star this repo and follow my other open source projects at https://github.com/alfg.

**Comment by sagar-monga** [comment]
Please assign Harvey Wallbanger.

**Comment by Nightowl-8** [comment]
can you tplease tell what exactly i have to do?

**Comment by alfg** [comment]
Hi @Nightowl-8, follow the [Contribution Guidelines](https://github.com/alfg/opendrinks/blob/master/CONTRIBUTING.md) for adding a recipe. Or feel free to find any bugs to fix.

**Comment by Nightowl-8** [comment]
Thanks @alfg

**Comment by manueldose** [comment]
Hi! Can i add a cocktail recipe ?

**Comment by alfg** [comment]
@manueldose yes go ahead and submit a PR with a new recipe.

**Comment by alfg** [comment]
Thanks for the contributions, all! See you next year!
