### ISSUE TITLE
Current page does not take filtration into account

### ISSUE THREAD

**Issue by zichi** [alfg/opendrinks#1069]
**Describe the bug**
When you are in the explorer view and go to page 6 for example and then filter on keywords, if there are fewer pages of results than the current it doesn't move to a page with content.

**To Reproduce**
1. Go to '/explore'
2. Go to page 6
3. Select a narrow filter - eg. 'Filters => Add keyword  => Mocktail'
4. Page is now empty

**Expected behavior**
I expect 1 of two scenarios to happen,
1. I get sent to page 1
2. I get sent to the last page

**Screenshots**
![no-items](https://user-images.githubusercontent.com/5538469/135616783-d62b3d4f-aa5a-4d6c-aaf3-e662163cc4d5.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 94.0.4606.61
 
**Smartphone (please complete the following information):**
 - Device: OnePlus 9 Pro
 - OS: Android
 - Browser: Chrome
  
 Fix proposed in #1070

**Comment by alfg** [comment]
@zichi Good find and thanks for the fix on #1070.
