### ISSUE TITLE
Change the Share layout in a multiple button styles

### ISSUE THREAD

**Issue by Torfab** [alfg/opendrinks#1088]
**Is your feature request related to a problem? Please describe.**

At the moment the shares buttons are tied with a dropdown (not compliant with dark mode) with some anchor elements, it leads to a weird behaviour where you can click just outside the text and miss the share functionality, plus it's an obsolete way to share contents

**Describe the solution you'd like**
I propose to change the "share" layout in a multiple buttons on the page OR in a single Share button that opens a modal with all the shares options

**Describe alternatives you've considered**
At least make the dropdown list dark mode compliant and avoid the weird click behaviour extending it for the whole element.

Do you agree on that, may I work on this?

**Comment by alfg** [comment]
Hey @Torfab, agreed and feel free to work on this. Thank you.

**Comment by alfg** [comment]
#1099
