### ISSUE TITLE
Support more language translations

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#1097]
`i18n` is now supported via #711 and #1090.  We're looking for contributors to support more language translations. 

We currently have support for languages:
* English - `en`
* Japanese - `ja`

Each component now has a `i18n` block to add in the translations for the appropriate language code. For example:
```
<i18n>
{
  "ja": {
    "Contributed by": "提供",
    "Ingredients": "材料",
    "Directions": "手順",
    "View full recipe at": "完全なレシピを見る",
    "Similar drinks": "似ているドリンク"
  }
}
</i18n>
```

Feel free to submit a PR to support another language. Thanks!

**Comment by DanTcheche** [comment]
Hi, I can add the Spanish translation, I also think it would be better to have all translations in a single file so in the future is easier to add new languages. I can also do that if you want.
Please assign the issue to me if you want to proceed.

Thank you!

**Comment by imtheu** [comment]
Hi, i can add the Brazilian Portuguese translation, please assign the issue to me too if you want to proceed.

Btw, I think I agree a bit with what DanTcheche said about the single file

**Comment by Xelaflash** [comment]
working on French translation too

**Comment by alfg** [comment]
Thanks all. Feel free to make the PR and I will review once I can.

**Comment by appledora** [comment]
Hi, I would like to add Bengali but confused about the process. Can someone elaborate?

**Comment by OscarRG** [comment]
Hello i would like to add a german translation

**Comment by goodgodth** [comment]
i would like to add Thai translation.

**Comment by alfg** [comment]
Thanks for the contributions, everyone!
