### ISSUE TITLE
Feature Request: Export recipes as a print-friendly page

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#133]
Would like a feature to have a print-friendly page for a recipe view.

Bonus points if it can export to a PDF file.

_Originally posted by @TobyAsE in https://github.com/alfg/opendrinks/issues/50#issuecomment-537696571_

**Comment by franciscoemanuel** [comment]
Working on it

**Comment by alfg** [comment]
Thanks @franciscoemanuel !
