### ISSUE TITLE
Feature request: Display similiar drinks on a recipe page

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#134]
> Add a similar drinks section for each recipe. Similar drinks are drinks that have common keywords/ingredients. We can limit the number of recommendation and pick the ones that have the most similarities.

_Originally posted by @VVNoodle in https://github.com/alfg/opendrinks/issues/50#issuecomment-537724513_

Open to feedback and suggestions. The UI should take advantage of Bootstrap Vue components if possible.

**Comment by VVNoodle** [comment]
On it!

**Comment by alfg** [comment]
Algorithm added on:
https://github.com/alfg/opendrinks/pull/173

UI to be implemented next.

**Comment by TobyAsE** [comment]
Are you working on the ui @VVNoodle or may I try to come up with something reasonable?

**Comment by VVNoodle** [comment]
nope i'm not it's all yours!

**Comment by TobyAsE** [comment]
I'll work on it.

**Comment by alfg** [comment]
Sounds good, @TobyAsE!

**Comment by TobyAsE** [comment]
See #252, I used the `b-card`
