### ISSUE TITLE
Receipe for Cashew Feni Punch

### ISSUE THREAD

**Issue by rittikadeb** [alfg/opendrinks#1387]
## Description
Cashew Feni is local Goan liquor. It is made using traditional methods from the cashew apple and hence considered organic.

**Comment by akash0708** [comment]
@alfg , is this project a part of hacktoberfest 2023?

**Comment by rittikadeb** [comment]
yes it is a part of Hacktoberfest

**Comment by alfg** [comment]
Sorry for the late response. It is not, but I have merged the latest PRs to count towards credit. Thanks.
