### ISSUE TITLE
Tag drink recipes with keywords

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#139]
We need help tagging drink recipes with keywords so we can improve our search function. We have many recipes that have no keywords tagged, as this was a new feature.

Example of a properly tagged drink:
https://github.com/alfg/opendrinks/blob/master/src/recipes/ginger-milk-tea.json#L49-L52

Some notable keywords to add:
* `non-alcoholic`
* `coffee`
* `tea`
* `vegan`
* `smoothie`

Keywords can be anywhere from 2-5 keywords describing the type of drink.

Feel free to contribute keywords for 1 drink or many! Any help is appreciated.

**Comment by sumanismcse** [comment]
I am adding keywords to three of the recipes.

**Comment by hillarysousa** [comment]
I'll be adding keywords too

**Comment by pedrowoy** [comment]
I'll add keywords too

**Comment by Vanoux** [comment]
I Checked and added keywords missing for recipes A to C

**Comment by Kenzo604** [comment]
Reviewed bottom up and added PR to tag some common keywords to recipes titled W-Z.

**Comment by M-McCallum** [comment]
Added keywords and fixed formatting, with a focus on the vegan keyword, A - P. 

PR's - https://github.com/alfg/opendrinks/pull/546, https://github.com/alfg/opendrinks/pull/548

**Comment by alfg** [comment]
Thank you all for participating in Hacktoberfest 2019! See you again next year!
