### ISSUE TITLE
Dead project ?

### ISSUE THREAD

**Issue by jcolfej** [alfg/opendrinks#1391]
Hi there!
Is the project still alive?
There are quite a few pull requests pending, especially with hacktoberfest...

**Comment by Kathuria** [comment]
@jcolfej : Yup looks like maintainer not maintaining this repo anymore, also noticed bot vulnerabilities fixes PR's as well.

**Comment by alfg** [comment]
Hey, it's not dead, but not actively maintained as often as I haven't had much time for OSS lately. The last Hackathon for this project was 2021.

I'll try to find some time to check out the open PRs this week.

**Comment by alfg** [comment]
Last minute, but I have reviewed and merged the latest PRs (except for those with errors).
