### ISSUE TITLE
Feature request: Truncate recipe descriptions on "Explore" view

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#190]
Some recipes have long descriptions and causes the formatting on the "Explore" page to be misaligned. 

I would like for the description to be truncated with an Ellipsis when viewing recipes on the Explore page. This should also help with the alignment and formatting of each recipe "card" on the Explore page.

For example:
![Capture](https://user-images.githubusercontent.com/702541/66249608-f5146100-e6ea-11e9-9c07-e8b6676f7da9.PNG)

The highlighted section should be hidden. So the user would need to navigate into the full recipe view in order to see the full description.

**Comment by edumello** [comment]
Can I work on this one?

**Comment by alfg** [comment]
Go for it @edumello !

**Comment by alfg** [comment]
Fixed on #194
