### ISSUE TITLE
Feature request: Search Drinks by Keywords

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#191]
OpenDrinks now has support for keywords!

Lets update our search function to support searching by keywords:
https://opendrinks.netlify.com/search

**Comment by Chrispy404** [comment]
Gave this one a crack. Was quite good fun! 

As mentioned in the pull request the search did come with one slightly annoying bug (non program breaking) where certain drinks are displayed when an empty space is entered. I'm not sure what causes this, whether its the search itself or something to do with those JSON objects. 

If anyone is able to solve this please let me know.

**Comment by alfg** [comment]
Thanks @Chrispy404! I'll open another issue for the bug described above. 

I'm also going to be opening one soon for the search results to show the keywords in the results!
