### ISSUE TITLE
Search displays max 10 items 

### ISSUE THREAD

**Issue by Chrispy404** [alfg/opendrinks#193]
Since the drinks list is growing and there are more ways to search of drinks, the search results should either use work the same way as "Explore" now does, or simply display more results. 

Currently if i search for 'Gin' as an ingredient the Negroni isn't shown due to its alphabetic placement. Funnily enough though the Dark and Stormy is returned due to the 'Gin' in 'ginger beer', although this would be another issue.

**Comment by alfg** [comment]
Ah, good point! I will increase the search results. I will increase to 50.

**Comment by alfg** [comment]
Should be updated now. I think 50 might be good for now, since there are plans to improve the search feature.

Let me know what you think?

**Comment by Chrispy404** [comment]
looks great for now!
