### ISSUE TITLE
Fix image sizes

### ISSUE THREAD

**Issue by edumello** [alfg/opendrinks#195]
Need to fix some drink image sizes.

They are breaking the explore page.
![image](https://user-images.githubusercontent.com/8681314/66250752-ee88f680-e789-11e9-959a-cc823c17058c.png)

**Comment by alfg** [comment]
Yeah, the contributing spec is 600x400px. However, some images were submitted with a similar size and I still approved. Is this something that can be fixed via CSS?

**Comment by alfg** [comment]
Fixed on https://github.com/alfg/opendrinks/pull/201. Thanks @alexjharrison!
