### ISSUE TITLE
Add a drink! 🍸

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#20]
Hacktoberfest starts today! Add your drink recipes by forking and submitting a pull request.

Check back for updates for upcoming challenges. I'll be adding feature requests and bug fix requests for varying difficulty levels.

Also, be sure to check out the [Contributing Guidelines](https://github.com/alfg/opendrinks/blob/master/CONTRIBUTING.md) before submitting a pull request. :)

Happy hacking!

**Comment by FarhiaM** [comment]
Hi! Can i work on this issue? :)

**Comment by alfg** [comment]
@FarhiaM go for it! Add a recipe! 🍸

**Comment by joamarderije** [comment]
Hi, I add up new type of drink in your list, one of the proud of mix by us Filipinos :D
