### ISSUE TITLE
Bug: Certain drinks are displayed when an empty space is entered in Search.

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#211]
> As mentioned in the #199 the search did come with one slightly annoying bug (non program breaking) where certain drinks are displayed when an empty space is entered. I'm not sure what causes this, whether its the search itself or something to do with those JSON objects. 

Example:
https://user-images.githubusercontent.com/29446717/66253294-39663680-e7a9-11e9-9ec2-aa9aa952b45a.png

If anyone is able to solve this please let me know.

_Originally posted by @Chrispy404 in https://github.com/alfg/opendrinks/issues/191#issuecomment-538635857_

**Comment by Chrispy404** [comment]
Also should note this bug is only relevant when searching by Keyword. When searching by ingredients and empty space does not return anything and when searching by name any name with a space in it is displayed.

**Comment by dgupta04** [comment]
Hey, I'd like to take this up!
