### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#225]
Discuss linting this project.

Currently there's an `.eslintrc.json` file, created by the `vue-cli` package. However, open to ideas to improve the linting and syntax style on this project.

**Comment by d-szymanski** [comment]
I've created a [PR](https://github.com/alfg/opendrinks/pull/235) with prettier that follows current rules.
I am all in for Airbnb style, as it's well known and supported project.

**Comment by alfg** [comment]
Sounds good. Checking it out now. I'm also all for airbnb style!

**Comment by alfg** [comment]
https://github.com/alfg/opendrinks/pull/235
