### ISSUE TITLE
Create test environment

### ISSUE THREAD

**Issue by VVNoodle** [alfg/opendrinks#264]
The project is getting bigger, and increased lines of code means increased possibility of bugs. 

Setting up a testing environment will help catalyze development of unit tests in the future, and so will prevent bugs that would've otherwise never been spotted before.

As @alfg proposed, test environment will include the use of jest and mocha since they support component and unit testing.

Suggested things to do:

- create jest and mocha config files
- create a doc on testing conventions (e.g. should be in __tests__ directory, end with *.spec.js, where to add mocks, ...)
- set up two simple examples: one for component testing, and another for unit testing
- maybe also take a look into [this](https://vue-test-utils.vuejs.org/)

**Comment by alfg** [comment]
Also, just to note: I'll be setting up a CI either via Github Actions or Travis to run these tests (and probably the linters). This way we can validate the incoming pull requests.

**Comment by alfg** [comment]
Ok, think I have Github Actions setup for running a `node install, build and test` workflow:
https://github.com/alfg/opendrinks/actions

You can see an example of the "checks" on this PR:
https://github.com/alfg/opendrinks/pull/266

**Comment by alfg** [comment]
Testing setup and example setup via https://github.com/alfg/opendrinks/pull/265

I'll create another issue for adding more tests.
