### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#281]
Tests are setup via Jest from https://github.com/alfg/opendrinks/pull/265.

Looking for contributors to help add more tests.

Test Example is located at:
https://github.com/alfg/opendrinks/tree/master/tests/unit 

See: [CONTRIBUTING.md](https://github.com/alfg/opendrinks/blob/master/CONTRIBUTING.md)

**Comment by alfg** [comment]
#286 Adds a couple more simple tests. As well as fixing the `require.context` issue.

**Comment by alfg** [comment]
#324

**Comment by gabbersepp** [comment]
I can try to add a few tests. I have never written tests for Vue but I am using Jest with React and enzyme. Should new tests be committed onto a new issue as it was done in #324?

**Comment by alfg** [comment]
> I can try to add a few tests. I have never written tests for Vue but I am using Jest with React and enzyme. Should new tests be committed onto a new issue as it was done in #324?

It's fine to create a PR without an attached issue. Or you can just link it to this one.

**Comment by alfg** [comment]
Thank you all for participating in Hacktoberfest 2019! See you again next year!
