### ISSUE TITLE
Unify the design

### ISSUE THREAD

**Issue by TobyAsE** [alfg/opendrinks#307]
There are a lot of inconsistencies in the design around the project. We should make sure that we use the same distances (margins, line-heights) everywhere, have common guide-lines (especially left and right) and so on. Right now there is a lot of different stuff loosely flying around.

![explore-filter](https://user-images.githubusercontent.com/6002167/66603219-fdb5dd00-ebab-11e9-8c95-162123a37e4d.PNG)
![explore-pagination](https://user-images.githubusercontent.com/6002167/66603385-6309ce00-ebac-11e9-8839-2213c43d9fc1.PNG)
![image](https://user-images.githubusercontent.com/6002167/66603649-e9beab00-ebac-11e9-87f7-b2b68d1faf27.png)
![image](https://user-images.githubusercontent.com/6002167/66603793-31ddcd80-ebad-11e9-913f-6664806f5dea.png)
![image](https://user-images.githubusercontent.com/6002167/66603928-6f425b00-ebad-11e9-909b-69c33b68b8cf.png)

**Comment by alfg** [comment]
Yeah, we don't have any design guidelines as it's still an early project and I've just been letting Bootstrap Vue do much of the UI work with some minor CSS modifications. However since there's been so many drastic changes lately, it might be a good idea to figure this out. 

What are some of your recommendations?

**Comment by TobyAsE** [comment]
I'll write some design guidelines and make a PR.
I'll define guidelines and standard-margins and whatever else comes to mind.
What really triggered me to open this issue was the way on the right side of the page nothing really aligns in #303 . After that I've noticed a lot of small things.
The cards used for the explore page and the similar drinks have different spacing horizontally and vertically. In general vertical spacing between elements is all over the place. The print button is slightly too high. The icon for favouring is just somewhere. The filter button doesn't align with the cards or the other way around. The pagination isn't aligned to anything. The menu could use some work, too. I personally don't like the way the tab-style looks.

**Comment by alfg** [comment]
OK, sounds good. I would like to keep the design minimal and sorta similar to how Github's layout looks (kinda why I like bootstrap's style).

It would be great if we can solve any of the guideline and global styling by adding a globals.css or something to override some of the Bootstrap styles that we want to modify. This way we can keep the style modifications out of any of the individual components.
