### ISSUE TITLE
Find typos in recipes

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#32]
Some recipes may have typos in their description or instructions. Feel free to send a PR to add a correction.

**Comment by robsel118** [comment]
Having a look at it, will PR if I find some.

**Comment by joamarderije** [comment]
are this issues resolve already ?

**Comment by alfg** [comment]
> 
> 
> are this issues resolve already ?

@joamarderije I'm leaving this issue open as we are getting PRs for recipes daily. So I'm sure there will always be some typos and grammar errors to correct. :slightly_smiling_face:

**Comment by alfg** [comment]
Thank you all for participating in Hacktoberfest 2019! See you again next year!
