### ISSUE TITLE
Add a Drink Recipe! 🍸

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#323]
Welcome to Hackoberfest 2019! Add your drink recipes by forking and submitting a pull request.

We're looking to build a collection of drink recipes of all types! View the website at:
https://opendrinks.netlify.com/

Also, be sure to check out the [Contributing Guidelines](https://github.com/alfg/opendrinks/blob/master/CONTRIBUTING.md) before submitting a pull request. :)

Happy hacking! 🎃

**Comment by tamarbuta** [comment]
Added Brandy Alexander

**Comment by anksos** [comment]
How can I commit on that specific Issue?

**Comment by alfg** [comment]
> 
> 
> How can I commit on that specific Issue?

Hi @anksos, you can just submit a PR with your drink recipe. It doesn't need to be committed on a specific issue, but you can just refer to #323 in the comment of the PR.

**Comment by anksos** [comment]
@alfg I tried like 10 times always fails on the PR like I don't have access to do it on the branch. I created even my own branch still fails.

**Comment by alfg** [comment]
@anksos Are you forking the project and committing the changes to your own fork?

**Comment by anksos** [comment]
I tried to fork the project and commit on the same fork and i have forked the project created a new branch and tried to commit there. Both of them not working :/

**Comment by alfg** [comment]
> @alfg I tried to fork the project and commit on the same fork and i have forked the project created a new branch and tried to commit there. Both of them not working :/

Are you sure you are forking it? I don't see the fork listed on your account.

**Comment by elliecodestheweb** [comment]
I hope I did this properly! Please let me know if I need to correct anything. Added Medicine Ball Tea to recipes.

**Comment by anksos** [comment]
@alfg can you check now if its okay?
