### ISSUE TITLE
UI elements are not getting rendered as intended

### ISSUE THREAD

**Issue by sounak98** [alfg/opendrinks#354]
- Similar Drinks heading is not displayed above the Similar Drinks section
- Source is displayed two times

**Reproduce error**
1. Go to "https://opendrinks.netlify.com/recipe/thandai" or any page with a source
2. See error

**Screenshots**
<img width="725" alt="Screenshot 2019-10-13 at 7 33 00 AM" src="https://user-images.githubusercontent.com/22390515/66709959-547a0d00-ed8c-11e9-8fa1-8417d69b2729.png">

**Desktop (please complete the following information):**
 - OS [Mac OSX 10.15]
 - Browser [Brave Browser: 0.69.132 Chromium: 77.0.3865.90]

**Comment by alfg** [comment]
I'm working on fixing this exact page right now, ha. It'll be fixed shortly. We just merged in a new layout and I also noticed this page rendering incorrectly.

**Comment by sounak98** [comment]
@alfg nevermind then

**Comment by alfg** [comment]
Can you re-check?

**Comment by sounak98** [comment]
<img width="760" alt="Screenshot 2019-10-13 at 8 04 01 AM" src="https://user-images.githubusercontent.com/22390515/66710135-0a932600-ed90-11e9-87f6-15a57c77e5b5.png">

The headings are misaligned and it looks weird. You can probably fix that.

**Comment by alfg** [comment]
Working on it!

**Comment by alfg** [comment]
Updated. Please check when you have a moment.

**Comment by sounak98** [comment]
Looks perfect 🎉

**Comment by alfg** [comment]
Awesome, thanks!
