### ISSUE TITLE
[Feature Request] Keyboard controls on search view results

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#357]
When searching for drinks, I would like to use my keyboard arrow keys to select a drink when more than 1 item is displayed in the results. 

For example, this would be ideal:
* Go to search
* Type in "colada". 4 results are rendered.
* Press keyboard down arrow key to select the Piña Colada and hit enter to load the recipe

~~Bonus points if you can fix the search issue when searching drinks with accented characters, like `ñ`. Currently, searching for `pina` does not find the `piña colada` recipe.~~ [Fixed in #358]

**Comment by kcusaac** [comment]
I'll fix the accent search.

**Comment by tummala-manasa** [comment]
Hello @alfg , I have done changes for the keyboard controls. Please review my PR. #375 . Thanks!

**Comment by alfg** [comment]
@tummala-manasa Thanks! I'll check it out soon.

**Comment by alfg** [comment]
@tummala-manasa added some suggestions on the PR whenever you have a moment to check it out.

**Comment by alfg** [comment]
Resolved on #375
