### ISSUE TITLE
Logo + Header should link to the homepage

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#37]
https://opendrinks.netlify.com

Update the logo and header so when clicked, they link to the homepage.

https://github.com/alfg/opendrinks/blob/d0eae5071644a2f2c27e383e6111fda69f17639f/src/App.vue#L5-L8

This may need to be implemented via Vue Router's `:to` feature.

**Comment by nimitbhargava** [comment]
@alfg I'd like to take up this issue. Is it okay?

**Comment by alfg** [comment]
This is currently being worked on https://github.com/alfg/opendrinks/pull/40

**Comment by nimitbhargava** [comment]
Alright 👍
