### ISSUE TITLE
Fix margin spacing for mobile devices

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#38]
https://opendrinks.netlify.com on iOS using an iPhone X looks like this:
![opendrinks-iphone](https://user-images.githubusercontent.com/702541/65931251-b9f9f100-e3bd-11e9-9dd1-6a519ec88a81.jpeg)

---

Add some margin-bottom spacing using Bootstrap's `mb` css class.

**Comment by soer7022** [comment]
This should be fixed by my pull request
