### ISSUE TITLE
[Help Wanted] Add Drink Categories

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#396]
As part of #395, we now have a new homepage with featured drinks via a config file:
https://github.com/alfg/opendrinks/blob/master/src/featured.json

This should map to an existing drink in the list of recipes:
https://github.com/alfg/opendrinks/tree/master/src/recipes

I'm looking for help building a list of drink categories for the homepage. Either post them here or submit a pull request with your drink category, description and list of drinks to include.

**Comment by elliecodestheweb** [comment]
I'd like to help by adding a category. "Cold Weather Favorites" - that way I can add more tea and coffee drinks!

**Comment by alfg** [comment]
@elliecodestheweb That would be great! Can you add it to [featured.json](https://github.com/alfg/opendrinks/blob/master/src/featured.json)?

**Comment by kirschstern** [comment]
Hi,

i made a pr, please have a look at [#404](https://github.com/alfg/opendrinks/pull/404)

**Comment by alfg** [comment]
@jazzninja That sounds good! I like this idea.

**Comment by alessandrojcm** [comment]
Hi, I would like to add a feature like "Hot Weather Recipes" for drinks that would be good for the beach or a hot summer day. Would that be ok?

**Comment by jazzninja** [comment]
@alfg i've made the add to package.json and run a localized dev build of the package to confirm it works. Works great and i've submitted a PR to you. Thanks again!

**Comment by alfg** [comment]
@alessandrojcm Yup, that's fine.

**Comment by alfg** [comment]
@kirschstern Thanks! I left a suggestion on the PR.

**Comment by SamuelPai** [comment]
Hi, I made a pull request for adding a new category for Strong Drinks (#463)!

**Comment by GwenBischoff** [comment]
Hey, I made a PR for the category milky heaven (#608).

**Comment by alfg** [comment]
@GwenBischoff Thanks, merged!

**Comment by drahenshaw** [comment]
Would it be too late to make a "college" or "Homecoming" category for drinks?

**Comment by alfg** [comment]
> 
> 
> Would it be too late to make a "college" or "Homecoming" category for drinks?

Go for it! 👍

**Comment by alfg** [comment]
Thank you all for the categories and for participating in Hacktoberfest 2019! See you again next year!
