### ISSUE TITLE
Feature request: Drink recipe sources

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#43]
Since many recipes may have come from another source, it would make sense to add an optional source URL to the recipe.

For example, on the recipe: https://opendrinks.netlify.com/recipe/bloody-mary:

After "Directions", we can add a section for attributing a source, formatted nicely.

![Capture](https://user-images.githubusercontent.com/702541/65932576-1d3a5200-e3c3-11e9-8d89-2a6594c132c2.PNG)

This requires 2 parts:
1) Updating the JSON recipe template
2) Updating the recipe component to display the source (if provided)
3) Updating documentation in CONTRIBUTING.md.

Open to suggestions.

**Comment by robsel118** [comment]
Looking at it, will PR

**Comment by alfg** [comment]
https://github.com/alfg/opendrinks/pull/65
