### ISSUE TITLE
Feature request: Title should contain the drink name

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#47]
The `<title />` of a recipe page should contain the drink name that is currently loaded.

For example, if viewing: https://opendrinks.netlify.com/recipe/cosmopolitan

The title of the browser tab/window should say:
`🍸 Open Drinks - Cosmopolitan`.

This will help with SEO and looks nice on navigation.

**Comment by robsel118** [comment]
Can I try this one out ?

**Comment by alfg** [comment]
@robsel118 go for it!

**Comment by alfg** [comment]
https://github.com/alfg/opendrinks/pull/60
