### ISSUE TITLE
[Hacktoberfest] Add a Drink Recipe! 

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#472]
There's still 10 days left of [Hackoberfest](https://hacktoberfest.digitalocean.com/) 2019! Add your drink recipes by forking and submitting a pull request.

We're looking to build a collection of drink recipes (and [categories](https://github.com/alfg/opendrinks/issues/396)) of all types! View the website at:
https://opendrinks.netlify.com/

Also, be sure to check out the Contributing Guidelines for the JSON spec and image sizing before submitting a pull request. :)

Happy hacking! 🎃

**Comment by M-McCallum** [comment]
added Snake Bite! PR-https://github.com/alfg/opendrinks/pull/545
