### ISSUE TITLE
Manifest Pointing to missing favicon

### ISSUE THREAD

**Issue by alexjharrison** [alfg/opendrinks#559]
![image](https://user-images.githubusercontent.com/8920897/67517466-aa925e80-f670-11e9-983f-c4cbb0af5b93.png)

In the manifest.json, it is pointing to a 192x192 & 512x512 favicon image.
https://github.com/alfg/opendrinks/blob/78e95fd7c020f8fe19c7dad329e6095a2100e609/public/manifest.json#L6

Either the manifest must be updated or the correct images must be created.

**Comment by alfg** [comment]
Thanks. Will look into this.
