### ISSUE TITLE
🎃 [Hacktoberfest] Add a Drink Recipe! 

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#633]
There's just a few days left of Hackoberfest 2019! Add your drink recipes by forking and submitting a pull request.

We're looking to build a collection of drink recipes (and categories) of all types! View the website at:
https://opendrinks.io

Also, be sure to check out the Contributing Guidelines for the JSON spec and image sizing before submitting a pull request. :)

Happy hacking! 🎃

**Comment by voodoods** [comment]
See also: https://github.com/alfg/opendrinks/pull/650

**Comment by alfg** [comment]
Thanks for contributing for Hacktoberfest 2019!
