### ISSUE TITLE
🎃 Welcome to Hacktoberfest! 🎃 

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#7]
![Hacktoberfest](https://hacktoberfest.digitalocean.com/assets/logo-hf19-full-10f3c000cea930c76acc1dedc516ea7118b95353220869a3051848e45ff1d656.svg)

# Welcome to [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

We're looking for more contributors to submit a drink recipe of their choice! Also feel free to suggest any changes or bug fixes!

More issues will be created soon with varying difficulty levels. Check back for updates!

* Be sure to sign up at https://hacktoberfest.digitalocean.com
* [Create a Pull Request ](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) **between October 1-31** of 2019 to count towards your 4 PRs
* See [Contributing Guidelines](https://github.com/alfg/opendrinks/blob/master/CONTRIBUTING.md)
* See https://hacktoberfest.digitalocean.com/details for more details
* Happy Hacking! 🎃 

Feel free to comment or ask any questions here as well.

**Comment by ConnectNitish** [comment]
I would like to contribute here. Is there any specific based drink can be added or it is open to all type of drinks.

**Comment by alfg** [comment]
@ConnectNitish Any kind of mixed drink or cocktail works.

**Comment by alfg** [comment]
Open to all drinks and will eventually add more search options to filter by drink types!

**Comment by alfg** [comment]
Thank you all for participating in Hacktoberfest 2019! See you again next year!
