### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by kavalcante** [alfg/opendrinks#711]
There's any plans for an i18n implementation for the project? I'd like to participate!

**Comment by alfg** [comment]
Hi @kavalcante, 

There are no plans currently for i18n, but PRs are welcome! 😄

**Comment by s-sasaki-0529** [comment]
Is this issue still active?

I'd like to use [vue-i18n](https://kazupon.github.io/vue-i18n/) to solve this.
I'm Japanese, so I'll translate to Japanese first, but I'll also make it easy to translate to other languages.

**Comment by alfg** [comment]
@s-sasaki-0529 yes it's still active. Feel free to give it a try!

**Comment by alfg** [comment]
Added via #1090. Thanks @s-sasaki-0529!

I'll open a follow-up issue for adding more languages support.
