### ISSUE TITLE
🎃 Welcome to Hacktoberfest 2020! 🎃

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#725]
![HF2020 Events 1600x400 Centered](https://user-images.githubusercontent.com/702541/94755105-35cba800-0348-11eb-85b5-3b531f53b0f7.png)

# Welcome to [Hacktoberfest](https://hacktoberfest.digitalocean.com/) 2020!

We're looking for contributors to submit a drink recipe of their choice! Also feel free to suggest any changes, bug fixes, or feature requests! All merged pull requests will be published to https://opendrinks.io/.

See release notes from Hacktoberfest 2019 for last year's contributions:
https://github.com/alfg/opendrinks/releases/tag/v1.0.0

More issues will be created soon with varying difficulty levels. Check back for updates!

* Be sure to sign up at https://hacktoberfest.digitalocean.com
* [Create a Pull Request ](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) **between October 1-31** of 2020 to count towards your 4 Pull Requests.
* See [Contributing Guidelines](https://github.com/alfg/opendrinks/blob/master/CONTRIBUTING.md)
* See https://hacktoberfest.digitalocean.com/details for more details
* Happy Hacking! 🎃 

**:warning: Please note, any spam pull requests will be marked as invalid and will not count towards your 4 PRs.**

Feel free to comment or ask any questions here as well.

**Comment by DevanshD3** [comment]
Hey! What exactly is the issue/bug that needs to be fixed ?

**Comment by alfg** [comment]
Hi @DevanshD3, 

There's no outstanding issues/bugs at the moment, but feel free to submit a drink recipe. I'll be adding more feature requests throughout the month.

**Comment by FionaFR** [comment]
Can you please add #hacktoberfest-accepted for this issue?

**Comment by alfg** [comment]
Hi @FionaFR, 

According to the guidelines, as long as the repository is tagged `hacktoberfest` and the PR is merged, then it will be accepted.
https://hacktoberfest.digitalocean.com/details#details

You can confirm your progress at:
https://hacktoberfest.digitalocean.com/profile

**Comment by strawberries73** [comment]
Hello,  I am new.  I would like to work on this.

**Comment by strawberries73** [comment]
Also I would like to fix some of the recipes for consistency.   I used to be a chef so I think the recipes should be displayed the same way.

**Comment by alfg** [comment]
Feel free to submit a recipe or add corrections, @strawberries73!

**Comment by strawberries73** [comment]
Thank you, I hope you don't mind that I did both.  And hopefully I have resolved the conflict.

**Comment by alfg** [comment]
Thanks all!
