### ISSUE TITLE
Dark mode Anomalous behaviour when going into single recipe pages

### ISSUE THREAD

**Issue by Torfab** [alfg/opendrinks#811]
I just noticed that light theme flash for an instant before going into dark mode on single recipe pages.

**Comment by KevinLu** [comment]
Can you describe which browser you used? I'm trying on Firefox 81.0.1 on Win10 and cannot reproduce this.

**Comment by alfg** [comment]
I'm also on Firefox 81.0.1/Win10, and I see the light theme flash while navigating between recipes.

**Comment by KevinLu** [comment]
Ah yes, now I see it when I navigate between recipe pages.

**Comment by alfg** [comment]
Fixed on #859
