### ISSUE TITLE
Add a drink! 🍸

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#882]
Add your drink recipes by forking and submitting a pull request.

Be sure to check out the [Contributing Guidelines ](https://github.com/alfg/opendrinks/blob/master/CONTRIBUTING.md )before submitting a pull request. :)

Happy hacking!

**Comment by archi15** [comment]
Please review my PR #907. Thanks!

**Comment by alivapriyadarshini5** [comment]
Added Cold Coffe recipe #939

**Comment by ch1771dr0b0** [comment]
Added The Bengal Tiger recipe.
