### ISSUE TITLE
[Hacktoberfest] Add a Drink Recipe!

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#977]
Just a few days left of Hackoberfest 2020! Add your drink recipes by forking and submitting a pull request.

We're looking to build a collection of drink recipes (and categories) of all types! View the website at:
https://opendrinks.io

Also, be sure to check out the [Contributing Guidelines ](https://github.com/alfg/opendrinks/blob/master/CONTRIBUTING.md)for the JSON spec and image sizing before submitting a pull request. :)

Happy hacking! 🎃

**Comment by Sumit2399** [comment]
Hi @alfg,can I contribute?

**Comment by alfg** [comment]
@Sumit2399 Go for it!

**Comment by Sumit2399** [comment]
Hi @alfg.Added a PR for the same issue.
Hoping for merge soon!
